### ISSUE TITLE
Feature: 他の文字化け文字もあります

### ISSUE THREAD

**Issue by sdfczyx** [yutotnh/wave-dash-unify#422]
## なぜ機能が欲しいのか
「№」 この文字も保存すると、文字化けになる

## 提案の説明
～ と同じように対応できますか、ご確認の程よろしくお願いいたします。

**Comment by yutotnh** [comment]
@sdfczyx 
イメージとしては、下記表の0xADE2で保存するように対応するという認識でよろしいでしょうか

| 置き換え前                 | 置き換え後            |
| ------------------------- | -------------------- |
| NUMERO SIGN(0x8FA2F1)     | NUMERO SIGN(0xADE2)  |

[eucJP-ms](https://www2d.biglobe.ne.jp/~msyk/charcode/cp932/eucJP-ms.html)を参考にしました。

**Comment by sdfczyx** [comment]
>イメージとしては、下記表の0xADE2で保存するように対応するという認識でよろしいでしょうか
はい、認識があっています。お願いいたします。

**Comment by sdfczyx** [comment]
JRがあっています、おいいたします。
________________________________
差出人: yutotnh ***@***.***>
送信日r: 2024年12月28日 6:40
宛先: yutotnh/wave-dash-unify ***@***.***>
CC: zhang yexiang ***@***.***>; Mention ***@***.***>
件名: Re: [yutotnh/wave-dash-unify] Feature: 他の文字化け文字もあります (Issue #422)


@sdfczyx<https://github.com/sdfczyx>
イメ`ジとしては、下表の0xADE2で保存するように辘工毪趣いφJRでよろしいでしょうか

置きQえ前   置きQえ後
NUMERO SIGN(0x8FA2F1)   NUMERO SIGN(0xADE2)

eucJP-ms<https://www2d.biglobe.ne.jp/~msyk/charcode/cp932/eucJP-ms.html>を参考にしました。

―

**Comment by yutotnh** [comment]
@sdfczyx 
#423で対応しました。

既にv0.2.0としてマーケットプレースにもリリース済みなので、拡張機能を更新していただければ利用可能です。

**Comment by sdfczyx** [comment]
試してみましたが、うまく変換できないようです。
